Repository terasolunaorg/tutorial-apps, pull requests merged in 2018-03, with the labels that each got.

#196 [5.1.x] move login.jsp to webapp/WEB-INF/views #174
  first-spring-security/scripts/convert-security-test.sh
  first-spring-security/scripts/convert-security-xml.sh
  first-spring-security/src/main/java/com/example/security/app/login/LoginController.java
  first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp
  first-spring-security/src/main/webapp/login.jsp
Labels: 5.1.2

#206 [5.1.x] fix bug that web browser does not close at the end of the test #183
  common/src/test/java/org/terasoluna/gfw/tutorial/selenium/FunctionTestSupport.java
Labels: 5.1.2, bug

#210 [5.1.x] reflect guideline change #172
  common/scripts/convert-common-css.sh
  todo/src/main/webapp/WEB-INF/views/todo/list.jsp
Labels: 5.1.2, task

#226 unify files creating way at secure-login-demo #225
  secure-login-demo/scripts/convert-secure-login-css.sh
  secure-login-demo/scripts/convert-secure-login-infra.sh
  secure-login-demo/scripts/convert-secure-login-jsp.sh
  secure-login-demo/scripts/convert-secure-login-properties.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/create-app.sh
  secure-login-demo/src/secure-login-domain/src/main/resources/META-INF/spring/secure-login-codelist.xml
  secure-login-demo/src/secure-login-domain/src/main/resources/META-INF/spring/secure-login-infra.xml
  secure-login-demo/src/secure-login-env/src/main/resources/META-INF/spring/secure-login-infra.properties
  secure-login-demo/src/secure-login-env/src/main/resources/dozer.properties
  secure-login-demo/src/secure-login-env/src/main/resources/log4jdbc.properties
  secure-login-demo/src/secure-login-env/src/main/resources/logback.xml
  secure-login-demo/src/secure-login-selenium/src/test/java/.gitkeep
  secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/secure-login-infra.properties
  secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/selenium.properties
  secure-login-demo/src/secure-login-web/src/main/resources/META-INF/spring/application.properties
  secure-login-demo/src/secure-login-web/src/main/resources/ValidationMessages.properties
  secure-login-demo/src/secure-login-web/src/main/resources/i18n/application-messages.properties
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/include.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/layout/header.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/layout/template.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/welcome/home.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/resources/app/css/styles.css
Labels: 5.5.0

#224 [5.0.x] fix artifact version. #80
  pom.xml
Labels: 5.0.3, bug

#227 [5.4.x] Correction of shell execution conditions, location and contents #188
  common/scripts/convert-common-css.sh
  first-spring-security/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/convert-todo-css.sh
  todo/scripts/convert-todo-infra.sh
  todo/scripts/create-app.sh
Labels: 5.4.2, improvement

#228 [5.3.x] Correction of shell execution conditions, location and contents #188
  common/scripts/convert-common-css.sh
  first-spring-security/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/convert-todo-css.sh
  todo/scripts/convert-todo-infra.sh
  todo/scripts/create-app.sh
Labels: 5.3.2, improvement

#229 [5.2.x] Correction of shell execution conditions, location and contents #188
  common/scripts/convert-common-css.sh
  first-spring-security/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/convert-todo-css.sh
  todo/scripts/convert-todo-infra.sh
  todo/scripts/create-app.sh
Labels: 5.2.2, improvement

#230 [5.0.x] Correction of shell execution conditions, location and contents #188
  common/scripts/convert-common-css.sh
  first-spring-security/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/convert-todo-css.sh
  todo/scripts/convert-todo-infra.sh
  todo/scripts/create-app.sh
Labels: 5.0.3, improvement

#231 [1.0.x] Correction of shell execution conditions, location and contents #188
  first-spring-security/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/convert-todo-infra.sh
  todo/scripts/create-app.sh
Labels: 1.0.7, improvement

#232 [5.4.x] Change spring-mvc-rest.xml creation method from copy to create #194
  todo-rest/scripts/convert-rest-xml.sh
  todo-rest/scripts/copy-sources.sh
  todo-rest/src/main/resources/META-INF/spring/spring-mvc-rest.xml
Labels: 5.4.2, task

#233 [5.3.x] Change spring-mvc-rest.xml creation method from copy to create #194
  todo-rest/scripts/convert-rest-xml.sh
  todo-rest/scripts/copy-sources.sh
  todo-rest/src/main/resources/META-INF/spring/spring-mvc-rest.xml
Labels: 5.3.2, task

#234 [5.2.x] Change spring-mvc-rest.xml creation method from copy to create #194
  todo-rest/scripts/convert-rest-xml.sh
  todo-rest/scripts/copy-sources.sh
  todo-rest/src/main/resources/META-INF/spring/spring-mvc-rest.xml
Labels: 5.2.2, task

#235 [5.0.x] Change spring-mvc-rest.xml creation method from copy to create #194
  todo-rest/scripts/convert-rest-xml.sh
  todo-rest/scripts/copy-sources.sh
  todo-rest/src/main/resources/META-INF/spring/spring-mvc-rest.xml
Labels: 5.0.3, task

#236 [1.0.x] Change spring-mvc-rest.xml creation method from copy to create #194
  todo-rest/scripts/convert-rest-xml.sh
  todo-rest/scripts/copy-sources.sh
  todo-rest/src/main/resources/META-INF/spring/spring-mvc-rest.xml
Labels: 1.0.7, task

#237 [5.4.x] unify TodoService.java and TodoServiceImpl.java creating way #217
  todo-rest/scripts/convert-rest-java.sh
  todo-rest/scripts/copy-sources.sh
  todo-rest/scripts/create-app.sh
  todo-rest/src-jpa/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src-mybatis3/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src-plain/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src/main/java/com/example/todo/domain/service/todo/TodoService.java
  todo/src-jpa/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo/src-mybatis3/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo/src-plain/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
Labels: 5.4.2

#238 [5.3.x] unify TodoService.java and TodoServiceImpl.java creating way #217
  todo-rest/scripts/convert-rest-java.sh
  todo-rest/scripts/copy-sources.sh
  todo-rest/scripts/create-app.sh
  todo-rest/src-jpa/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src-mybatis3/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src-plain/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src/main/java/com/example/todo/domain/service/todo/TodoService.java
  todo/src-jpa/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo/src-mybatis3/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo/src-plain/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
Labels: 5.3.2

#239 [5.2.x] unify TodoService.java and TodoServiceImpl.java creating way #217
  todo-rest/scripts/convert-rest-java.sh
  todo-rest/scripts/copy-sources.sh
  todo-rest/scripts/create-app.sh
  todo-rest/src-jpa/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src-mybatis3/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src-plain/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src/main/java/com/example/todo/domain/service/todo/TodoService.java
  todo/src-jpa/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo/src-mybatis3/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo/src-plain/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
Labels: 5.2.2

#240 [5.0.x] unify TodoService.java and TodoServiceImpl.java creating way #217
  todo-rest/scripts/convert-rest-java.sh
  todo-rest/scripts/copy-sources.sh
  todo-rest/scripts/create-app.sh
  todo-rest/src-jpa/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src-mybatis3/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src-plain/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src/main/java/com/example/todo/domain/service/todo/TodoService.java
  todo/src-jpa/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo/src-mybatis3/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo/src-plain/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
Labels: 5.0.3

#243 [5.4.x] modify jsp indent 4 spaces #179
  first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp
Labels: 5.4.2

#244 [5.3.x] modify jsp indent 4 spaces #179
  first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp
Labels: 5.3.2

#245 [5.2.x] modify jsp indent 4 spaces #179
  first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp
Labels: 5.2.2

#247 [1.0.x] delete unnecessary login.jsp #246
  first-spring-security/src/main/webapp/login.jsp
Labels: 1.0.7

#249 [5.1.x] modify jsp indent 4 spaces #179
  first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp
Labels: 5.1.2

#241 [1.0.x] unify TodoService.java and TodoServiceImpl.java creating way #217
  todo-rest/scripts/convert-rest-java.sh
  todo-rest/scripts/copy-sources.sh
  todo-rest/scripts/create-app.sh
  todo-rest/src/main/java/com/example/todo/domain/service/todo/TodoService.java
  todo-rest/src/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo/src/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
Labels: 1.0.7

#222 [5.2.x] Reflect blank project change #149
  secure-login-demo/src/secure-login-domain/src/main/resources/META-INF/spring/secure-login-codelist.xml
  secure-login-demo/src/secure-login-domain/src/main/resources/META-INF/spring/secure-login-infra.xml
  secure-login-demo/src/secure-login-env/src/main/resources/logback.xml
Labels: 5.2.2

#252 [5.5.x]Session Tutorial Application is not implemented for tiles #248
  session-tutorial-complete/scripts/convert-session-complete-java.sh
  session-tutorial-complete/scripts/convert-session-complete-jsp.sh
  session-tutorial-complete/scripts/convert-session-complete-properties.sh
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateConfirm.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateFinish.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm1.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm2.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/cart/viewCart.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/confirm.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/finish.jsp
  session-tutorial-init/scripts/convert-session-init-jsp.sh
  session-tutorial-init/scripts/convert-session-init-properties.sh
  session-tutorial-init/src/session-tutorial-init-web/src/main/java/com/example/session/app/goods/GoodsController.java
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createConfirm.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createFinish.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createForm.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoods.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoodsDetail.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/login/loginForm.jsp
Labels: 5.5.0

#254 Fix selenium version to 2.46.0 #139
  common/scripts/convert-common-test.sh
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/create-app.sh
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.5.0, bug

#242 Remove the target-project folder before mkdir target-project #181
  .gitignore
  common/scripts/convert-common-test.sh
  first-spring-security/scripts/convert-security-jsp.sh
  first-spring-security/scripts/convert-security-test.sh
  first-spring-security/scripts/convert-security-xml.sh
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/convert-secure-login-css.sh
  secure-login-demo/scripts/convert-secure-login-infra.sh
  secure-login-demo/scripts/convert-secure-login-jsp.sh
  secure-login-demo/scripts/convert-secure-login-properties.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/create-app.sh
  session-tutorial-complete/scripts/convert-session-complete-css.sh
  session-tutorial-complete/scripts/convert-session-complete-java.sh
  session-tutorial-complete/scripts/convert-session-complete-jsp.sh
  session-tutorial-complete/scripts/convert-session-complete-properties.sh
  session-tutorial-complete/scripts/convert-session-complete-test.sh
  session-tutorial-complete/scripts/convert-session-complete-xml.sh
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/convert-session-init-css.sh
  session-tutorial-init/scripts/convert-session-init-jsp.sh
  session-tutorial-init/scripts/convert-session-init-properties.sh
  session-tutorial-init/scripts/convert-session-init-test.sh
  session-tutorial-init/scripts/convert-session-init-xml.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/convert-rest-java.sh
  todo-rest/scripts/convert-rest-msg.sh
  todo-rest/scripts/convert-rest-test.sh
  todo-rest/scripts/convert-rest-xml.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/convert-todo-css.sh
  todo/scripts/convert-todo-infra.sh
  todo/scripts/convert-todo-test.sh
  todo/scripts/create-app.sh
Labels: 5.5.0, improvement

#255 [5.1.x] unify TodoService.java and TodoServiceImpl.java creating way #217
  todo-rest/scripts/convert-rest-java.sh
  todo-rest/scripts/copy-sources.sh
  todo-rest/scripts/create-app.sh
  todo-rest/src-jpa/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src-mybatis3/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src-plain/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src/main/java/com/example/todo/domain/service/todo/TodoService.java
  todo/src-jpa/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo/src-mybatis3/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo/src-plain/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
Labels: 5.1.2

#256 [5.1.x] Correction of shell execution conditions, location and contents #188
  common/scripts/convert-common-css.sh
  first-spring-security/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/convert-todo-css.sh
  todo/scripts/convert-todo-infra.sh
  todo/scripts/create-app.sh
Labels: 5.1.2, improvement

#257 [5.1.x] Change spring-mvc-rest.xml creation method from copy to create #194
  todo-rest/scripts/convert-rest-xml.sh
  todo-rest/scripts/copy-sources.sh
  todo-rest/src/main/resources/META-INF/spring/spring-mvc-rest.xml
Labels: 5.1.2, task

#258 [5.4.x] unify files creating way at secure-login-demo #225
  secure-login-demo/scripts/convert-secure-login-css.sh
  secure-login-demo/scripts/convert-secure-login-infra.sh
  secure-login-demo/scripts/convert-secure-login-jsp.sh
  secure-login-demo/scripts/convert-secure-login-properties.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/create-app.sh
  secure-login-demo/src/secure-login-domain/src/main/resources/META-INF/spring/secure-login-codelist.xml
  secure-login-demo/src/secure-login-domain/src/main/resources/META-INF/spring/secure-login-infra.xml
  secure-login-demo/src/secure-login-env/src/main/resources/META-INF/spring/secure-login-infra.properties
  secure-login-demo/src/secure-login-env/src/main/resources/dozer.properties
  secure-login-demo/src/secure-login-env/src/main/resources/log4jdbc.properties
  secure-login-demo/src/secure-login-env/src/main/resources/logback.xml
  secure-login-demo/src/secure-login-selenium/src/test/java/.gitkeep
  secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/secure-login-infra.properties
  secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/selenium.properties
  secure-login-demo/src/secure-login-web/src/main/resources/META-INF/spring/application.properties
  secure-login-demo/src/secure-login-web/src/main/resources/ValidationMessages.properties
  secure-login-demo/src/secure-login-web/src/main/resources/i18n/application-messages.properties
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/include.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/layout/header.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/layout/template.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/welcome/home.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/resources/app/css/styles.css
Labels: 5.4.2

#259 [5.3.x] unify files creating way at secure-login-demo #225
  secure-login-demo/scripts/convert-secure-login-css.sh
  secure-login-demo/scripts/convert-secure-login-infra.sh
  secure-login-demo/scripts/convert-secure-login-jsp.sh
  secure-login-demo/scripts/convert-secure-login-properties.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/create-app.sh
  secure-login-demo/src/secure-login-domain/src/main/resources/META-INF/spring/secure-login-codelist.xml
  secure-login-demo/src/secure-login-domain/src/main/resources/META-INF/spring/secure-login-infra.xml
  secure-login-demo/src/secure-login-env/src/main/resources/META-INF/spring/secure-login-infra.properties
  secure-login-demo/src/secure-login-env/src/main/resources/dozer.properties
  secure-login-demo/src/secure-login-env/src/main/resources/log4jdbc.properties
  secure-login-demo/src/secure-login-env/src/main/resources/logback.xml
  secure-login-demo/src/secure-login-selenium/src/test/java/.gitkeep
  secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/secure-login-infra.properties
  secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/selenium.properties
  secure-login-demo/src/secure-login-web/src/main/resources/META-INF/spring/application.properties
  secure-login-demo/src/secure-login-web/src/main/resources/ValidationMessages.properties
  secure-login-demo/src/secure-login-web/src/main/resources/i18n/application-messages.properties
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/include.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/layout/header.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/layout/template.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/welcome/home.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/resources/app/css/styles.css
Labels: 5.3.2

#260 [5.2.x] unify files creating way at secure-login-demo #225
  secure-login-demo/scripts/convert-secure-login-css.sh
  secure-login-demo/scripts/convert-secure-login-infra.sh
  secure-login-demo/scripts/convert-secure-login-jsp.sh
  secure-login-demo/scripts/convert-secure-login-properties.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/create-app.sh
  secure-login-demo/src/secure-login-domain/src/main/resources/META-INF/spring/secure-login-codelist.xml
  secure-login-demo/src/secure-login-domain/src/main/resources/META-INF/spring/secure-login-infra.xml
  secure-login-demo/src/secure-login-env/src/main/resources/META-INF/spring/secure-login-infra.properties
  secure-login-demo/src/secure-login-env/src/main/resources/dozer.properties
  secure-login-demo/src/secure-login-env/src/main/resources/log4jdbc.properties
  secure-login-demo/src/secure-login-env/src/main/resources/logback.xml
  secure-login-demo/src/secure-login-selenium/src/test/java/.gitkeep
  secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/secure-login-infra.properties
  secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/selenium.properties
  secure-login-demo/src/secure-login-web/src/main/resources/META-INF/spring/application.properties
  secure-login-demo/src/secure-login-web/src/main/resources/ValidationMessages.properties
  secure-login-demo/src/secure-login-web/src/main/resources/i18n/application-messages.properties
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/include.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/layout/header.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/layout/template.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/welcome/home.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/resources/app/css/styles.css
Labels: 5.2.2

#261 [5.4.x] Fix selenium version to 2.46.0 #139
  common/scripts/convert-common-test.sh
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/create-app.sh
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.4.2, bug

#262 [5.3.x] Fix selenium version to 2.46.0 #139
  common/scripts/convert-common-test.sh
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/create-app.sh
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.3.2, bug

#263 [5.4.x]Session Tutorial Application is not implemented for tiles #248
  session-tutorial-complete/scripts/convert-session-complete-java.sh
  session-tutorial-complete/scripts/convert-session-complete-jsp.sh
  session-tutorial-complete/scripts/convert-session-complete-properties.sh
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateConfirm.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateFinish.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm1.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm2.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/cart/viewCart.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/confirm.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/finish.jsp
  session-tutorial-init/scripts/convert-session-init-jsp.sh
  session-tutorial-init/scripts/convert-session-init-properties.sh
  session-tutorial-init/src/session-tutorial-init-web/src/main/java/com/example/session/app/goods/GoodsController.java
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createConfirm.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createFinish.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createForm.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoods.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoodsDetail.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/login/loginForm.jsp
Labels: 5.4.2

#250 unify application database bean and test database bean in selenium #251 remove postgres setting #253
  secure-login-demo/scripts/convert-secure-login-infra.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/copy-sources.sh
  secure-login-demo/src/secure-login-initdb/src/main/sqls/postgres/01-schema.sql
  secure-login-demo/src/secure-login-initdb/src/main/sqls/postgres/02-dataload.sql
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/AccountLockTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/InputValidationTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/PasswordLeakageMeasuresTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/PasswordReissueTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/PasswordStrengthTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/SecureLoggingTest.java
  secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/secure-login-infra.properties
  secure-login-demo/src/secure-login-selenium/src/test/resources/database/PostgreSQL-datareload.sql
Labels: 5.5.0, bug

#219 Change groupId to a fixed value. Change artifactId to provide default values. #215
  .travis.yml
  docs/README.md
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/convert-secure-login-jsp.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/create-app.sh
  secure-login-demo/src/secure-login-env/configs/context.xml
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.5.0, bug

#264 [5.4.x] Remove the target-project folder before mkdir target-project #181
  .gitignore
  common/scripts/convert-common-test.sh
  first-spring-security/scripts/convert-security-jsp.sh
  first-spring-security/scripts/convert-security-test.sh
  first-spring-security/scripts/convert-security-xml.sh
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/convert-secure-login-css.sh
  secure-login-demo/scripts/convert-secure-login-infra.sh
  secure-login-demo/scripts/convert-secure-login-jsp.sh
  secure-login-demo/scripts/convert-secure-login-properties.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/create-app.sh
  session-tutorial-complete/scripts/convert-session-complete-css.sh
  session-tutorial-complete/scripts/convert-session-complete-java.sh
  session-tutorial-complete/scripts/convert-session-complete-jsp.sh
  session-tutorial-complete/scripts/convert-session-complete-properties.sh
  session-tutorial-complete/scripts/convert-session-complete-test.sh
  session-tutorial-complete/scripts/convert-session-complete-xml.sh
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/convert-session-init-css.sh
  session-tutorial-init/scripts/convert-session-init-jsp.sh
  session-tutorial-init/scripts/convert-session-init-properties.sh
  session-tutorial-init/scripts/convert-session-init-test.sh
  session-tutorial-init/scripts/convert-session-init-xml.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/convert-rest-java.sh
  todo-rest/scripts/convert-rest-msg.sh
  todo-rest/scripts/convert-rest-test.sh
  todo-rest/scripts/convert-rest-xml.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/convert-todo-css.sh
  todo/scripts/convert-todo-infra.sh
  todo/scripts/convert-todo-test.sh
  todo/scripts/create-app.sh
Labels: 5.4.2, improvement

#265 [5.3.x] Remove the target-project folder before mkdir target-project #181
  .gitignore
  common/scripts/convert-common-test.sh
  first-spring-security/scripts/convert-security-jsp.sh
  first-spring-security/scripts/convert-security-test.sh
  first-spring-security/scripts/convert-security-xml.sh
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/convert-secure-login-css.sh
  secure-login-demo/scripts/convert-secure-login-infra.sh
  secure-login-demo/scripts/convert-secure-login-jsp.sh
  secure-login-demo/scripts/convert-secure-login-properties.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/create-app.sh
  session-tutorial-complete/scripts/convert-session-complete-css.sh
  session-tutorial-complete/scripts/convert-session-complete-java.sh
  session-tutorial-complete/scripts/convert-session-complete-jsp.sh
  session-tutorial-complete/scripts/convert-session-complete-properties.sh
  session-tutorial-complete/scripts/convert-session-complete-test.sh
  session-tutorial-complete/scripts/convert-session-complete-xml.sh
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/convert-session-init-css.sh
  session-tutorial-init/scripts/convert-session-init-jsp.sh
  session-tutorial-init/scripts/convert-session-init-properties.sh
  session-tutorial-init/scripts/convert-session-init-test.sh
  session-tutorial-init/scripts/convert-session-init-xml.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/convert-rest-java.sh
  todo-rest/scripts/convert-rest-msg.sh
  todo-rest/scripts/convert-rest-test.sh
  todo-rest/scripts/convert-rest-xml.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/convert-todo-css.sh
  todo/scripts/convert-todo-infra.sh
  todo/scripts/convert-todo-test.sh
  todo/scripts/create-app.sh
Labels: 5.3.3, improvement

#266 [5.2.x] Remove the target-project folder before mkdir target-project #181
  .gitignore
  first-spring-security/scripts/convert-security-jsp.sh
  first-spring-security/scripts/convert-security-test.sh
  first-spring-security/scripts/convert-security-xml.sh
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/convert-secure-login-css.sh
  secure-login-demo/scripts/convert-secure-login-infra.sh
  secure-login-demo/scripts/convert-secure-login-jsp.sh
  secure-login-demo/scripts/convert-secure-login-properties.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/create-app.sh
  session-tutorial-complete/scripts/convert-session-complete-css.sh
  session-tutorial-complete/scripts/convert-session-complete-java.sh
  session-tutorial-complete/scripts/convert-session-complete-jsp.sh
  session-tutorial-complete/scripts/convert-session-complete-properties.sh
  session-tutorial-complete/scripts/convert-session-complete-test.sh
  session-tutorial-complete/scripts/convert-session-complete-xml.sh
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/convert-session-init-css.sh
  session-tutorial-init/scripts/convert-session-init-jsp.sh
  session-tutorial-init/scripts/convert-session-init-properties.sh
  session-tutorial-init/scripts/convert-session-init-test.sh
  session-tutorial-init/scripts/convert-session-init-xml.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/convert-rest-java.sh
  todo-rest/scripts/convert-rest-msg.sh
  todo-rest/scripts/convert-rest-test.sh
  todo-rest/scripts/convert-rest-xml.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/convert-todo-css.sh
  todo/scripts/convert-todo-infra.sh
  todo/scripts/convert-todo-test.sh
  todo/scripts/create-app.sh
Labels: 5.2.2, improvement

#267 [5.1.x] unify files creating way at secure-login-demo #225
  secure-login-demo/scripts/convert-secure-login-css.sh
  secure-login-demo/scripts/convert-secure-login-infra.sh
  secure-login-demo/scripts/convert-secure-login-jsp.sh
  secure-login-demo/scripts/convert-secure-login-properties.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/create-app.sh
  secure-login-demo/src/secure-login-env/src/main/resources/META-INF/spring/secure-login-infra.properties
  secure-login-demo/src/secure-login-env/src/main/resources/dozer.properties
  secure-login-demo/src/secure-login-env/src/main/resources/log4jdbc.properties
  secure-login-demo/src/secure-login-selenium/src/test/java/.gitkeep
  secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/secure-login-infra.properties
  secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/selenium.properties
  secure-login-demo/src/secure-login-selenium/src/test/resources/database/H2-datareload.sql
  secure-login-demo/src/secure-login-selenium/src/test/resources/database/PostgreSQL-datareload.sql
  secure-login-demo/src/secure-login-web/src/main/resources/META-INF/spring/application.properties
  secure-login-demo/src/secure-login-web/src/main/resources/ValidationMessages.properties
  secure-login-demo/src/secure-login-web/src/main/resources/i18n/application-messages.properties
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/businessError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/systemError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/include.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/layout/header.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/layout/template.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/welcome/home.jsp
  secure-login-demo/src/secure-login-web/src/main/webapp/resources/app/css/styles.css
Labels: 5.1.2

#274 [5.0.x] Remove the target-project folder before mkdir target-project #181
  .gitignore
  first-spring-security/scripts/convert-security-jsp.sh
  first-spring-security/scripts/convert-security-test.sh
  first-spring-security/scripts/convert-security-xml.sh
  first-spring-security/scripts/create-app.sh
  todo-rest/scripts/convert-rest-java.sh
  todo-rest/scripts/convert-rest-msg.sh
  todo-rest/scripts/convert-rest-test.sh
  todo-rest/scripts/convert-rest-xml.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/convert-todo-css.sh
  todo/scripts/convert-todo-infra.sh
  todo/scripts/convert-todo-test.sh
  todo/scripts/create-app.sh
Labels: 5.0.3, improvement

#275 [1.0.x] Remove the target-project folder before mkdir target-project #181
  .gitignore
  first-spring-security/scripts/convert-security-jsp.sh
  first-spring-security/scripts/convert-security-test.sh
  first-spring-security/scripts/convert-security-xml.sh
  first-spring-security/scripts/create-app.sh
  todo-rest/scripts/convert-rest-java.sh
  todo-rest/scripts/convert-rest-msg.sh
  todo-rest/scripts/convert-rest-test.sh
  todo-rest/scripts/convert-rest-xml.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/convert-todo-infra.sh
  todo/scripts/convert-todo-test.sh
  todo/scripts/create-app.sh
Labels: 1.0.7, improvement

#280 [5.1.x] Remove the target-project folder before mkdir target-project #181
  .gitignore
  first-spring-security/scripts/convert-security-jsp.sh
  first-spring-security/scripts/convert-security-test.sh
  first-spring-security/scripts/convert-security-xml.sh
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/convert-secure-login-css.sh
  secure-login-demo/scripts/convert-secure-login-infra.sh
  secure-login-demo/scripts/convert-secure-login-jsp.sh
  secure-login-demo/scripts/convert-secure-login-properties.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/create-app.sh
  session-tutorial-complete/scripts/convert-session-complete-css.sh
  session-tutorial-complete/scripts/convert-session-complete-java.sh
  session-tutorial-complete/scripts/convert-session-complete-jsp.sh
  session-tutorial-complete/scripts/convert-session-complete-properties.sh
  session-tutorial-complete/scripts/convert-session-complete-test.sh
  session-tutorial-complete/scripts/convert-session-complete-xml.sh
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/convert-session-init-css.sh
  session-tutorial-init/scripts/convert-session-init-jsp.sh
  session-tutorial-init/scripts/convert-session-init-properties.sh
  session-tutorial-init/scripts/convert-session-init-test.sh
  session-tutorial-init/scripts/convert-session-init-xml.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/convert-rest-java.sh
  todo-rest/scripts/convert-rest-msg.sh
  todo-rest/scripts/convert-rest-test.sh
  todo-rest/scripts/convert-rest-xml.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/convert-todo-css.sh
  todo/scripts/convert-todo-infra.sh
  todo/scripts/convert-todo-test.sh
  todo/scripts/create-app.sh
Labels: 5.1.2, improvement

#281 [5.4.x] unify application database bean and test database bean in selenium #251 remove postgres setting #253
  secure-login-demo/scripts/convert-secure-login-infra.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/copy-sources.sh
  secure-login-demo/src/secure-login-initdb/src/main/sqls/postgres/01-schema.sql
  secure-login-demo/src/secure-login-initdb/src/main/sqls/postgres/02-dataload.sql
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/AccountLockTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/InputValidationTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/PasswordLeakageMeasuresTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/PasswordReissueTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/PasswordStrengthTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/SecureLoggingTest.java
  secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/secure-login-infra.properties
  secure-login-demo/src/secure-login-selenium/src/test/resources/database/PostgreSQL-datareload.sql
Labels: 5.4.2, bug, improvement

#283 [5.2.x] unify application database bean and test database bean in selenium #251 remove postgres setting #253
  secure-login-demo/scripts/convert-secure-login-infra.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/copy-sources.sh
  secure-login-demo/src/secure-login-initdb/src/main/sqls/postgres/01-schema.sql
  secure-login-demo/src/secure-login-initdb/src/main/sqls/postgres/02-dataload.sql
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/AccountLockTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/InputValidationTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/PasswordLeakageMeasuresTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/PasswordReissueTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/PasswordStrengthTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/SecureLoggingTest.java
  secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/secure-login-infra.properties
  secure-login-demo/src/secure-login-selenium/src/test/resources/database/PostgreSQL-datareload.sql
Labels: 5.2.2, bug, improvement

#282 [5.3.x] unify application database bean and test database bean in selenium #251 remove postgres setting #253
  secure-login-demo/scripts/convert-secure-login-infra.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/copy-sources.sh
  secure-login-demo/src/secure-login-initdb/src/main/sqls/postgres/01-schema.sql
  secure-login-demo/src/secure-login-initdb/src/main/sqls/postgres/02-dataload.sql
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/AccountLockTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/InputValidationTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/PasswordLeakageMeasuresTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/PasswordReissueTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/PasswordStrengthTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/SecureLoggingTest.java
  secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/secure-login-infra.properties
  secure-login-demo/src/secure-login-selenium/src/test/resources/database/PostgreSQL-datareload.sql
Labels: 5.3.3, bug, improvement

#284 [5.1.x] unify application database bean and test database bean in selenium #251 remove postgres setting #253
  secure-login-demo/scripts/convert-secure-login-infra.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/copy-sources.sh
  secure-login-demo/src/secure-login-initdb/src/main/sqls/postgres/01-schema.sql
  secure-login-demo/src/secure-login-initdb/src/main/sqls/postgres/02-dataload.sql
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/AccountLockTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/PasswordLeakageMeasuresTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/PasswordReissueTest.java
  secure-login-demo/src/secure-login-selenium/src/test/java/com/example/securelogin/selenium/loginform/PasswordStrengthTest.java
  secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/secure-login-infra.properties
  secure-login-demo/src/secure-login-selenium/src/test/resources/database/PostgreSQL-datareload.sql
Labels: 5.1.2, bug, improvement

#285 [5.4.x] Change groupId to a fixed value. Change artifactId to provide default values. #215
  .travis.yml
  docs/README.md
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/convert-secure-login-jsp.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/create-app.sh
  secure-login-demo/src/secure-login-env/configs/context.xml
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.4.2, bug

#286 [5.3.x] Change groupId to a fixed value. Change artifactId to provide default values. #215
  .travis.yml
  docs/README.md
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/convert-secure-login-jsp.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/create-app.sh
  secure-login-demo/src/secure-login-env/configs/context.xml
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.3.3, bug

#287 [5.2.x] Change groupId to a fixed value. Change artifactId to provide default values. #215
  .travis.yml
  docs/README.md
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/convert-secure-login-jsp.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/create-app.sh
  secure-login-demo/src/secure-login-env/configs/context.xml
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.2.2, bug

#288 [5.1.x] Change groupId to a fixed value. Change artifactId to provide default values. #215
  .travis.yml
  docs/README.md
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/convert-secure-login-jsp.sh
  secure-login-demo/scripts/convert-secure-login-test.sh
  secure-login-demo/scripts/convert-secure-login-xml.sh
  secure-login-demo/scripts/create-app.sh
  secure-login-demo/src/secure-login-env/configs/context.xml
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.1.2, bug

#289 [5.0.x] Change groupId to a fixed value. Change artifactId to provide default values. #215
  .travis.yml
  docs/README.md
  first-spring-security/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.0.3, bug

#276 [5.3.x]Session Tutorial Application is not implemented for tiles #248
  session-tutorial-complete/scripts/convert-session-complete-java.sh
  session-tutorial-complete/scripts/convert-session-complete-jsp.sh
  session-tutorial-complete/scripts/convert-session-complete-properties.sh
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateConfirm.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateFinish.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm1.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm2.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/cart/viewCart.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/confirm.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/finish.jsp
  session-tutorial-init/scripts/convert-session-init-jsp.sh
  session-tutorial-init/scripts/convert-session-init-properties.sh
  session-tutorial-init/src/session-tutorial-init-web/src/main/java/com/example/session/app/goods/GoodsController.java
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createConfirm.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createFinish.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createForm.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoods.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoodsDetail.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/login/loginForm.jsp
Labels: 5.3.3

#295 fix archetypeVersion for 5.0.x #215
  first-spring-security/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.0.3, bug

#294 fix archetypeVersion for 5.1.x #215
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/create-app.sh
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.1.2, bug

#293 fix archetypeVersion for 5.2.x #215
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/create-app.sh
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.2.2, bug

#292 fix archetypeVersion for 5.3.x #215
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/create-app.sh
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.3.3, bug

#291 fix archetypeVersion for 5.4.x #215
  first-spring-security/scripts/create-app.sh
  secure-login-demo/scripts/create-app.sh
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.4.2, bug

#290 [1.0.x] Change groupId to a fixed value. Change artifactId to provide default values. #215
  .travis.yml
  docs/README.md
  first-spring-security/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 1.0.7, bug

#296 [5.4.x] update snapshot version to 5.4.2 #279
  .travis.yml
  first-spring-security/scripts/create-app.sh
  pom.xml
  secure-login-demo/scripts/create-app.sh
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.4.2

#297 [5.3.x] update snapshot version to 5.3.3 #279
  .travis.yml
  first-spring-security/scripts/create-app.sh
  pom.xml
  secure-login-demo/scripts/create-app.sh
  session-tutorial-complete/scripts/create-app.sh
  session-tutorial-init/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/create-app.sh
Labels: 5.3.3

#277 [5.2.x]Session Tutorial Application is not implemented for tiles #248
  session-tutorial-complete/scripts/convert-session-complete-java.sh
  session-tutorial-complete/scripts/convert-session-complete-jsp.sh
  session-tutorial-complete/scripts/convert-session-complete-properties.sh
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateConfirm.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateFinish.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm1.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm2.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/cart/viewCart.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/confirm.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/finish.jsp
  session-tutorial-init/scripts/convert-session-init-jsp.sh
  session-tutorial-init/scripts/convert-session-init-properties.sh
  session-tutorial-init/src/session-tutorial-init-web/src/main/java/com/example/session/app/goods/GoodsController.java
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createConfirm.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createFinish.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createForm.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoods.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoodsDetail.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/login/loginForm.jsp
Labels: 5.2.2

#278 [5.1.x]Session Tutorial Application is not implemented for tiles #248
  session-tutorial-complete/scripts/convert-session-complete-java.sh
  session-tutorial-complete/scripts/convert-session-complete-jsp.sh
  session-tutorial-complete/scripts/convert-session-complete-properties.sh
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateConfirm.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateFinish.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm1.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm2.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/cart/viewCart.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/confirm.jsp
  session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/finish.jsp
  session-tutorial-init/scripts/convert-session-init-jsp.sh
  session-tutorial-init/scripts/convert-session-init-properties.sh
  session-tutorial-init/src/session-tutorial-init-web/src/main/java/com/example/session/app/goods/GoodsController.java
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createConfirm.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createFinish.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createForm.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoods.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoodsDetail.jsp
  session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/login/loginForm.jsp
Labels: 5.1.2
