Repository terasolunaorg/tutorial-apps, pull requests merged in 2018-02, with the labels that each got.

#184 fix bug that web browser does not close at the end of the test #183
  common/src/test/java/org/terasoluna/gfw/tutorial/selenium/FunctionTestSupport.java
Labels: 5.5.0, bug

#186 [5.3.x] Move login.jsp from just below webapp to webapp/WEB-INF/views/login #174
  first-spring-security/scripts/convert-security-test.sh
  first-spring-security/scripts/convert-security-xml.sh
  first-spring-security/src/main/java/com/example/security/app/login/LoginController.java
  first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp
  first-spring-security/src/main/webapp/login.jsp
Labels: 5.3.2

#178 [5.4.x] move login.jsp to webapp/WEB-INF/views #174
  first-spring-security/scripts/convert-security-test.sh
  first-spring-security/scripts/convert-security-xml.sh
  first-spring-security/src/main/java/com/example/security/app/login/LoginController.java
  first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp
  first-spring-security/src/main/webapp/login.jsp
Labels: 5.4.1

#191 [5.2.x] Travis CI Broken using Selenium #152 #154
  .travis.yml
  session-tutorial-complete/src/session-tutorial-complete-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java
  session-tutorial-init/src/session-tutorial-init-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java
Labels: 5.2.2, bug

#195 Change spring-mvc-rest.xml creation method from copy to create #194
  todo-rest/scripts/convert-rest-xml.sh
  todo-rest/scripts/copy-sources.sh
  todo-rest/src/main/resources/META-INF/spring/spring-mvc-rest.xml
Labels: 5.5.0, task

#192 [5.1.x] Travis CI Broken using Selenium #152 #154
  .travis.yml
  session-tutorial-complete/src/session-tutorial-complete-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java
  session-tutorial-init/src/session-tutorial-init-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java
Labels: 5.1.2, bug

#190 Correction of shell execution conditions, location and contents #188
  common/scripts/convert-common-css.sh
  first-spring-security/scripts/create-app.sh
  todo-rest/scripts/create-app.sh
  todo/scripts/convert-todo-css.sh
  todo/scripts/convert-todo-infra.sh
  todo/scripts/create-app.sh
Labels: 5.5.0, improvement

#180 modify loginForm.jsp indent 4 spaces #179
  first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp
Labels: 5.5.0

#187 [5.2.x] move login.jsp to webapp/WEB-INF/views #174
  first-spring-security/scripts/convert-security-test.sh
  first-spring-security/scripts/convert-security-xml.sh
  first-spring-security/src/main/java/com/example/security/app/login/LoginController.java
  first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp
  first-spring-security/src/main/webapp/login.jsp
Labels: 5.2.2

#197 [1.0.x] move login.jsp to webapp/WEB-INF/views #174
  first-spring-security/scripts/convert-security-test.sh
  first-spring-security/scripts/convert-security-xml.sh
  first-spring-security/src/main/java/com/example/security/app/login/LoginController.java
  first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp
Labels: 1.0.7

#200 [5.4.x] reflect guideline change #172
  common/scripts/convert-common-css.sh
  todo/src/main/webapp/WEB-INF/views/todo/list.jsp
Labels: 5.4.1, task

#201 [5.3.x] reflect guideline change #172
  common/scripts/convert-common-css.sh
  todo/src/main/webapp/WEB-INF/views/todo/list.jsp
Labels: 5.3.2, task

#202 [5.2.x] reflect guideline change #172
  common/scripts/convert-common-css.sh
  todo/src/main/webapp/WEB-INF/views/todo/list.jsp
Labels: 5.2.2, task

#211 [5.0.x] reflect guideline change #172
  common/scripts/convert-common-css.sh
  todo/src/main/webapp/WEB-INF/views/todo/list.jsp
Labels: task

#212 [1.0.x] reflect guideline change #172
  todo/src/main/webapp/WEB-INF/views/todo/list.jsp
Labels: 1.0.7, task

#203 [5.4.x] fix bug that web browser does not close at the end of the test #183
  common/src/test/java/org/terasoluna/gfw/tutorial/selenium/FunctionTestSupport.java
Labels: 5.4.1, bug

#204 [5.3.x] fix bug that web browser does not close at the end of the test #183
  common/src/test/java/org/terasoluna/gfw/tutorial/selenium/FunctionTestSupport.java
Labels: 5.3.2, bug

#205 [5.2.x] fix bug that web browser does not close at the end of the test #183
  common/src/test/java/org/terasoluna/gfw/tutorial/selenium/FunctionTestSupport.java
Labels: 5.2.2, bug

#207 [5.0.x] fix bug that web browser does not close at the end of the test #183
  common/src/test/java/org/terasoluna/gfw/tutorial/selenium/FunctionTestSupport.java
Labels: bug

#208 [1.0.x] fix bug that web browser does not close at the end of the test #183
  common/src/test/java/org/terasoluna/gfw/tutorial/selenium/FunctionTestSupport.java
Labels: 1.0.7, bug

#216 fix does not work to the screen to complete creation of new account #213
  secure-login-demo/src/secure-login-web/src/main/java/com/example/securelogin/app/account/AccountController.java
Labels: 5.5.0, bug

#218 fix the request to the password change screen is set to POST #214
  secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/account/view.jsp
Labels: 5.5.0, bug

#221 unify TodoService.java and TodoServiceImpl.java creating way #217
  todo-rest/scripts/convert-rest-java.sh
  todo-rest/scripts/copy-sources.sh
  todo-rest/scripts/create-app.sh
  todo-rest/src-jpa/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src-mybatis3/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src-plain/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo-rest/src/main/java/com/example/todo/domain/service/todo/TodoService.java
  todo/src-jpa/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo/src-mybatis3/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
  todo/src-plain/main/java/com/example/todo/domain/service/todo/TodoServiceImpl.java
Labels: 5.5.0
